### ISSUE TITLE
Domaine Halyna

### ISSUE THREAD

**Issue by arthaud-proust** [les-voix-errantes-de-kyiv/3-halyna#1]
# Configuration du sous domaine de votre projet
- [x] Ajoutez "3-halyna.les-voix-errantes-de-kyiv.fr" en tant que nom de domaine sur votre hébergeur (vercel, netlify, etc)
- [x] **Répondez ci-dessous quel hébergeur vous utilisez pour que je fasse pointer le domaine dessus.**

Merci !
Dispo pour toute question

**Comment by tmiia** [comment]
Hello, on utilise Netlify

**Comment by arthaud-proust** [comment]
Coucou ! ok j'ai modifié le record dns, ça pointe vers Netlify. Vous aurez sans doute à revenir dans la gestion des domaines pour dire à Netlify que c'est bon

Merci !

Tenez moi au courant si y'a un pb

**Comment by arthaud-proust** [comment]
C'est tout bon, merci !

**Comment by arthaud-proust** [comment]
Hello,
Vous pouvez ajouter le nom de domaine `halyna.les-voix-errantes-de-kyiv.fr` dans votre hébergeur.
L'ancienne adresse redirigera vers la nouvelle, comme ça si vous avez fait un qr code il fonctionnera toujours.
